export enum PerkType {
    GYM = "GYM",
    MIDDLE_SCHOOL = "MIDDLE_SCHOOL",
    PRE_SCHOOL = "PRE_SCHOOL",
    HIGH_SCHOOL = "HIGH_SCHOOL",
    KINDERGARDEN = "KINDERGARDEN",
    GROCERY_STORE = "GROCERY_STORE",
    RESTAURANT = "RESTAURANT",
    PARK = "PARK"
}