spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/home_radar_db
    username: admin
    password: admin
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  mail:
    host: smtp.gmail.com
    port: 587
    username: quick.ride.mk@gmail.com
    password: rnit lurr vyky tcki

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    # Uncomment below if you want to set dialect explicitly
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.PostgreSQL95Dialect

  flyway:
  # enabled: true
  # baseline-on-migrate: true

  web:
    resources:
      static-locations:
        - classpath:/static/
          - file:uploads/
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

stripe:
  secret-key: {{STRIPE_SECRET_KEY}}
  publishable-key: {{STRIPE_PUBLISHABLE_KEY}}
  webhook:
    secret: {{STRIPE_WEBHOOK_SECRET}}
  price-id-standard: {{STRIPE_STANDARD_PLAN_PRICE_ID}}
  price-id-premium: {{STRIPE_PREMIUM_PLAN_PRICE_ID}}

app:
  frontend:
    url: https://home-radar.mk:4200

ml:
  pricing:
    for-rent:
      url: http://127.0.0.1:8000/predict
      model: XGBoost
    for-sale:
      url: http://127.0.0.1:8002/predict
      model: CatBoost